/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1f2638",
        "on-tertiary-fixed": "#090d18",
        "on-tertiary-container": "#9c8f73",
        "on-surface": "#f4efe4",
        "tertiary-container": "#e8d8ad",
        "outline": "#c7ad6a",
        "primary-fixed-dim": "#b99345",
        "inverse-on-surface": "#101828",
        "surface-dim": "#050814",
        "secondary": "#b9c6df",
        "on-error-container": "#ffdad6",
        "surface": "#070b18",
        "on-primary-fixed": "#18110a",
        "error": "#ffb4ab",
        "secondary-fixed": "#d8e0f0",
        "on-tertiary-fixed-variant": "#6f5f3c",
        "on-background": "#f4efe4",
        "inverse-surface": "#f4efe4",
        "tertiary-fixed-dim": "#bfa96c",
        "surface-container-highest": "#172033",
        "secondary-fixed-dim": "#aebbd5",
        "surface-container-high": "#11192b",
        "surface-container-lowest": "#030611",
        "secondary-container": "#273553",
        "on-tertiary": "#101828",
        "tertiary-fixed": "#f2e4bc",
        "surface-bright": "#1e2940",
        "surface-container-low": "#0b1020",
        "on-primary-container": "#2e210d",
        "on-secondary-container": "#d9e2f3",
        "on-error": "#690005",
        "on-secondary": "#1d2840",
        "background": "#050814",
        "primary": "#d7b66a",
        "tertiary": "#fff8e9",
        "on-primary": "#141006",
        "surface-container": "#0d1425",
        "inverse-primary": "#8a6a2f",
        "primary-fixed": "#f4da96",
        "primary-container": "#f0c96f",
        "surface-tint": "#d7b66a",
        "outline-variant": "#4f452c",
        "on-secondary-fixed-variant": "#455371",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#6f5120",
        "surface-variant": "#182236",
        "on-surface-variant": "#b9b2a3"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
