/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#23005c",
        "on-tertiary-fixed": "#1b1b1d",
        "on-tertiary-container": "#605f62",
        "on-surface": "#e5e2e3",
        "tertiary-container": "#dddadd",
        "outline": "#849495",
        "primary-fixed-dim": "#00dbe7",
        "inverse-on-surface": "#313031",
        "surface-dim": "#131314",
        "secondary": "#d0bcff",
        "on-error-container": "#ffdad6",
        "surface": "#131314",
        "on-primary-fixed": "#002022",
        "error": "#ffb4ab",
        "secondary-fixed": "#e9ddff",
        "on-tertiary-fixed-variant": "#474649",
        "on-background": "#e5e2e3",
        "inverse-surface": "#e5e2e3",
        "tertiary-fixed-dim": "#c8c6c8",
        "surface-container-highest": "#353436",
        "secondary-fixed-dim": "#d0bcff",
        "surface-container-high": "#2a2a2b",
        "surface-container-lowest": "#0e0e0f",
        "secondary-container": "#571bc1",
        "on-tertiary": "#303032",
        "tertiary-fixed": "#e5e1e4",
        "surface-bright": "#3a393a",
        "surface-container-low": "#1c1b1c",
        "on-primary-container": "#006a71",
        "on-secondary-container": "#c4abff",
        "on-error": "#690005",
        "on-secondary": "#3c0091",
        "background": "#131314",
        "primary": "#e1fdff",
        "tertiary": "#faf6f9",
        "on-primary": "#00363a",
        "surface-container": "#201f20",
        "inverse-primary": "#00696f",
        "primary-fixed": "#74f5ff",
        "primary-container": "#00f2ff",
        "surface-tint": "#00dbe7",
        "outline-variant": "#3a494b",
        "on-secondary-fixed-variant": "#5516be",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#004f54",
        "surface-variant": "#353436",
        "on-surface-variant": "#b9cacb"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
